export const countries = [{value: "Australia", name: "AU"},
{value: "Austria", name:"AT"},
{value: "Azerbaijan", name:"AZ"},
{value: "Belgium", name:	"BE"},
{value:"Chile", name: "CL"},
{value:"China", name: "CN"},
{value:"Hong Kong", name: "HK"},
{value:"Macao", name: "MO"},
{value:"Finland", name:	"FI"},
{value:"France", name:	"FR"},
{value:"Germany", name:	"DE"},
{value:"India", name:	"IN"},
{value:"Indonesia", name:	"ID"},
{value:"Netherlands", name:	"NL"},
{value:"Pakistan", name:"PK"},
{value:"Qatar", name:	"QA"},
{value:"United Arab Emirates", name:	"AE"},
{value:"United Kingdom", name:	"GB"},
{value:"United States of America", name:"US"}]